---
- name: Set hostname
  hostname: name={{ inventory_hostname }}
  become: yes

- name: Update /etc/hosts
  lineinfile:
      dest=/etc/hosts
      regexp="^127\.0\.1\.1"
      line="127.0.1.1{{ '\t' }}{{ inventory_hostname }}"
      state=present
  become: yes

- name: Check the hostname
  fail: msg='Invalid hostname'
  when: ansible_hostname != inventory_hostname

- name: Get the hostname
  debug: msg='Guten tag! Ich heiße {{ ansible_hostname }}'
